const express = require('express');
const path = require('path');
const cors = require('cors');
const authMid = require('./middleware/auth');
const app = express();
app.use(cors());
app.use(express.json());
app.use(express.static(path.join(__dirname,'public')));
app.use('/api/auth', require('./routes/auth'));
app.use('/api/persons', authMid, require('./routes/persons'));
app.use('/api/finance', authMid, require('./routes/finance'));
app.use('/api/dashboard', authMid, require('./routes/dashboard'));
app.use('/api/notifications', authMid, require('./routes/notifications'));
app.use('/api/attendance', authMid, require('./routes/attendance'));
app.use('/api', authMid, require('./routes/attendance'));
const PORT = process.env.PORT||3000;
app.listen(PORT, ()=>console.log('running on '+PORT));
